Operations_db:
  assert_db: true
  backup: false
  recovery: false
bidDocReferEndTime: 2024-10-01
bidDocReferEndTimeCus: 2024-10-01
bidOpenTime: '2024-10-29 15:20:59'
bidSectionName: 测试接口自动化项目标段
case_ids:
  case_id: b30
database:
  dev:
    data:
      database: mydb
      host: 192.168.4.82
      password: d3d644bb
      port: 5432
      user: qy_admin
    db_type: postgresql
  prod:
    data:
      database: ry-vue
      host: 192.168.1.234
      password: '123456'
      port: 3306
      user: root
    db_type: mysql
  test:
    data:
      database: qy_biz_open_eval
      host: 192.168.4.82
      password: d3d644bb
      port: 3306
      user: qy_admin
    db_type: mysql
docGetEndTime: 2024-10-01
docGetEndTimeCus: 2024-10-01
email:
  addressees:
  - 397135766@qq.com
  - huangpeng245@163.com
  contents: 解压allure-report.zip(接口测试报告)后，进入解压目录，运行Start_server.bat（需要有python环境），在浏览器输入http://127.0.0.1:5188/allure-report
    即可查看测试报告。出现“Serving HTTP on 0.0.0.0 port 5188 (http://0.0.0.0:5188/) ...”表示服务启动完成，可以输入
    http://127.0.0.1:5188/allure-report 地址查看报告
  enclosures: ./report_zip/allure-report.zip
  host: smtp.163.com
  password: DYTKTEPXOZXXZMHK
  title: 接口自动化测试报告(见附件)
  user: huoyan_hyh@163.com
extra_pool:
  Aprtoken: eyJ4NXQjUzI1NiI6Im02OXFnMnMxeE1NQkFuRFBtLTRyYkZSanNpRWxJSkVSOVRRbTVfT256RmMiLCJraWQiOiJiaWRkaW5nIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIxNzg5MjE0NzM3ODcyMTEzNjY0IiwiYXVkIjoiNWRkZmE2ODJkZWQyZWVjOWI1MGI4OTE5YzhmYTRjNDQiLCJuYmYiOjE3MzY5MjA3NTgsImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzM2OTI3OTU4LCJpYXQiOjE3MzY5MjA3NTgsImp0aSI6IjU0MzlhMWM1YTk2NjRmYmRhY2YyYzQ0MjhlZjIzMDg4In0.Ae-zDCobKFILaQN2BRmQwVSjsB3vbmIH35BIU1NXfsFO4gb7UwAQNSqFkF1fvmD9I_xmAPBlCsy4Bg0I3wwwTacl8fityQcxyav7T-eNKhUnYBUtRXRLJddYGEtwb73YJNTVD0x4F9KH74nHvZiw4MkjPS31Wz3nC8hVvv5LIkGdf0YHKcvS3ZWfX2jAwPHGOGP90RFxo-8dsBvTkypPURlrmHauYevWfTXcfFlHvIJqZnLy0TtHCig0Um5GIl87qWqFFc1yMI6sD9xte46sQIwc3TE8-Ipj4nD1ciP3LGrdZih52S0ySZB_xBfukDEhqZxO8Ont48cvrOQaWsys5g
  OpenTime: '2024-10-29 15:10:57'
  PROJECT_NAME: $.project_name
  _ERROR: ' 0'
  _FAILED: ' 0'
  _PASSED: '0'
  _SKIPPED: ' 0'
  _SUCCESS_RATE: '0.00'
  _TIMES: 0.0 s
  _TOTAL: '0'
  audittoken: $.data.access_token
  audittoken1: eyJ4NXQjUzI1NiI6Im02OXFnMnMxeE1NQkFuRFBtLTRyYkZSanNpRWxJSkVSOVRRbTVfT256RmMiLCJraWQiOiJiaWRkaW5nIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIxODUzMjUxMDQ5MzU2NDQ3NzQ0IiwiYXVkIjoiNWRkZmE2ODJkZWQyZWVjOWI1MGI4OTE5YzhmYTRjNDQiLCJuYmYiOjE3MzMxMjc0NTksImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMzMTM0NjU5LCJpYXQiOjE3MzMxMjc0NTksImp0aSI6IjA0NzQwNDYwNDE3MjRjM2JiZWExZWM4MmZhZDczNjJjIn0.YPkLfZiCRt4DTLsfh3zg1iKtWvrGB4c5kbnJrwK9a-3ivjVhoaLin9sTrBG3R36pTS58my4NAIe8zDuQUV3-UO8vsKVNxcsK90721RuDBNas2sNhDK5Nb0zvqB2HX-epFN-6EFJLJlXfwsu8Yh8QPG55hMZnzH_5LJ3anPypYdgqMfNIkB45e4XTD4b1M7oxVYkVlBLy1h4hYD6U-4pmCrQ3LUVx6_FgeojZH5Wn6Rtno8yVJnE2ZGj9QVlRT63IOJApICDXXn-Or2TfMBibROrli454hKp9kfmoYPqbgeMSh5TjoXdq2ShBYZb-D4kKtGatH6ZgNQ37dRlkGx8t2w
  bidDeptId1: $.data[0].bidDeptId
  bidDeptId2: $.data[1].bidDeptId
  bidDeptId3: $.data[2].bidDeptId
  bidDocReferEndTime: '2025-02-15 17:36:54'
  bidDocReferEndTimeCus: '2025-02-15 17:36:54'
  bidOpenTime: '2025-02-15 17:36:54'
  bidSectionCode: E130600545600005i001001
  bidSectionId: '1879407946316038146'
  bidSectionName: 企采-测试接口自动化项目2025-01-15 13:59:02-标段01
  bidSectionName1: 测试接口自动化项目2025-01-15 13:59:02-标段01
  bidSectionName1Decode: '%E6%B5%8B%E8%AF%95%E6%8E%A5%E5%8F%A3%E8%87%AA%E5%8A%A8%E5%8C%96%E9%A1%B9%E7%9B%AE2025-01-15%2013%3A59%3A02-%E6%A0%87%E6%AE%B501'
  bidSectionName2: 测试接口自动化项目2025-01-15 13:59:02-标段02
  bidSectionName2Decode: '%E6%B5%8B%E8%AF%95%E6%8E%A5%E5%8F%A3%E8%87%AA%E5%8A%A8%E5%8C%96%E9%A1%B9%E7%9B%AE2025-01-15%2013%3A59%3A02-%E6%A0%87%E6%AE%B502'
  bulletinId: $.data.list[0].bulletinId
  docGetEndTime: '2025-02-15 17:36:54'
  docGetEndTimeCus: '2025-02-15 17:36:54'
  env: test
  evaluation_method: '1'
  fileId: $.data.id
  fileNum: 0
  fileUrl: $.data[0].fileUrl
  fileid: $.data
  firstAprPsw: HH_tT0fpkhgzoIIar7auoZm4iwjsDZwiGdYH2zl7jx4s/dV4idZ_eq8W/0/7NufMQNqdaQogk1xsg3GwPsZj6DWhfAr9hFlQDBW3thSkw4TdWi7P7iNyky0OXAWg8r2LS371UK2m4cNGq7ZcGhutwq64peVm9bBuFKtZT2Uwdis=
  firstAprUser: 河北代清
  guaranteeType: ''
  ifFee: ''
  ifJudgesConfirmWinBidder: 'false'
  ifSupportBlindBid: 'false'
  ifSupportSmallMicro: 'false'
  ifSyndicatedFlag: 'false'
  ifUseCa: 'false'
  inviteType: '1'
  itemid: '1855903699903414273'
  judge1: $.data[0].expertPhone
  judge2: $.data[1].expertPhone
  judge3: $.data[2].expertPhone
  judgeid1: $.data[0].expertUserId
  judgeid2: $.data[1].expertUserId
  judgeid3: $.data[2].expertUserId
  judgepwd1: YWAV/Q3B6ttmsQYqdYXq1I6N9vag0HnNTgpKiXbqH6ixAAjVui4Ol9h2wAqZJ7tnhmsLP2lJRvvfdMe2nRxC1HNIcSFzlczEQXo29aEdG3_hdKzMpgfuFrSkUAYVaHM2tsHhGbVNc7M2C6hy4TdCV89VXSTBQJrQ2yH5HZNzENA=
  judgepwd2: JhGEdk8tLty1cJn/wGdllXLHNNSf6znuyfag9JPxBTlZLpnDc68wLYEVzo_mSxllMqie9LtvOA2G4M1RdB3BTWL4ktWbxwclnq1xD3TbXHsBY7qDkPeKt6ZHR2a59QcmeyzMLQ4tZUi93O8BDHaoyMiLoH/_tEGPH7Lsrw9WR5c=
  judgepwd3: d6Jts/VpDnWlKVhROMmgzqCl1_l61cIZ/2EaKjzgVqmFpzdc8OiglULZ7t0q7qjTBKruABk2cf4Kd_xJasXHxJ//6nyshLMx5grwzrVLagNLhC7BQ8UbsfewItmdph54egMBZBLJ9K9ntJIU22vbWv9LqjrkjfUNHc3JuAOyysY=
  judgetoken1: $.data.access_token
  judgetoken2: eyJ4NXQjUzI1NiI6Im02OXFnMnMxeE1NQkFuRFBtLTRyYkZSanNpRWxJSkVSOVRRbTVfT256RmMiLCJraWQiOiJiaWRkaW5nIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIxODQ5MDExMDM0NDAxMTk4MDgwIiwiYXVkIjoiNWRkZmE2ODJkZWQyZWVjOWI1MGI4OTE5YzhmYTRjNDQiLCJuYmYiOjE3MzEzMTgxOTMsImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMxMzI1MzkzLCJpYXQiOjE3MzEzMTgxOTMsImp0aSI6ImJhNTI2Yzg2ZmI5MDRjMDFiY2RhMTA1MTNmZDRiN2JiIn0.JKcnqtpA6ros7r_X_hFjEAAAWnSPIsikcNBxTZ2eg5zZcm2sJ9b7BYJg73WWoDiHCoBRf0VuLfL-h0wr6AcBjrB6l1HWAxXHl5LDCcVBcJrwEBiMFEJhyEBNbXJJydLT_AXf2Hd9Aobh_5TeZEIDeWgPwqdhNjgB6O90KR-y2h7NCD4HsMzVxSdzQDX5zpOesLzCwPttFG_SGWvrf7uabdrTxTiU-qFNp4C7-kORnCFdlX4BLzNYaDkZ8tGyGbpoEm8UmHnnZ-lKeV8V-yjlojOC3TPNFUeayKKMSKRJU4bPAiCuKzMV_UwtKu2wChX953GxAkgfh_37rWrKpGtTzQ
  judgetoken3: eyJ4NXQjUzI1NiI6Im02OXFnMnMxeE1NQkFuRFBtLTRyYkZSanNpRWxJSkVSOVRRbTVfT256RmMiLCJraWQiOiJiaWRkaW5nIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIxODQ5MDExMDM2NDE4NjU4MzA0IiwiYXVkIjoiNWRkZmE2ODJkZWQyZWVjOWI1MGI4OTE5YzhmYTRjNDQiLCJuYmYiOjE3MzEzMTgxNjEsImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMxMzI1MzYxLCJpYXQiOjE3MzEzMTgxNjEsImp0aSI6IjQ2MzFiMWZmMDliMjQ0YjQ5NjZhMDA1OWEwYTYxYTM5In0.T0EHjaDvNra8IwP0Hm8bqGyqDn7LZR2F31X59JTop0C-fPWrPXHKwVQShc3xB3D1HnxsN4YzIn7LcAnaS2cLAw8RVyWXNp7GXLf2aqFoNp2M8Ac9HjZiW9867ok6IQgoQv3VnXHyjtKz78FSAw2GQzBwvAvrgXsCWyrlzQQrSvLonX1T5BGTnXJulhvORYIwv54N4FJ-qYH7SvvEPnTdULv0GVZ5grQ9vhkP0UrSmblopeJ9Bzf5qBM4iFsyi-LU9WGCUz6sUHh8LohXChT_I5VYJmlOMUo_rPbnc4YtmLeuYp8TXyPbhXJ92onjgN0sdWqVnNzsgKCnKgLI9AiA3A
  juryid: $.data.list[0].id
  marginPrice: '0'
  marginUnit: '0'
  noticeEndTime: '2025-02-15 17:36:54'
  noticeSendTime: '2025-01-26 17:41:54'
  password: LU8gv_kGm7edkUJQKMEeWKtnG3/OXwEZHSaCxWDcdQUDuw8to66Wb3BU3_fVzpq66AiSIhpbuugYAnhorAbSEVRmYeny8GzpHet4UvZ0kROw_q/d6EYNl7ugmEldTJHp6iBzcPDJBHEy13gWq8nH5K6GlFJRHJHJasnXI4Zdt30=
  pqrMode: '2'
  purchas_project_id: $.data.list[0].id
  purchaseMode: '1'
  purchaseProjectCode: $.data.list[0].purchaseProjectCode
  purchaseProjectName: 测试接口自动化项目2025-01-26 17:36:54
  purchaseProjectNameDecode: '%E6%B5%8B%E8%AF%95%E6%8E%A5%E5%8F%A3%E8%87%AA%E5%8A%A8%E5%8C%96%E9%A1%B9%E7%9B%AE2025-01-26%2017%3A36%3A54'
  purchaseProjectType: D03
  sectionId: $.data.list[0].id
  stepId: $.data.evalStepDetailDTOList[0].tfEvaluateStepDTO.id
  stepId1: '1855903699777585153'
  stepId2: '1673423311428'
  stepId3: '1673423311429'
  stepId4: '1673423462862'
  tenderOrganizeForm: '1'
  tfId: '1879408019489865729'
  tfPrice: '0'
  tfid: $.data
  token: eyJ4NXQjUzI1NiI6Im02OXFnMnMxeE1NQkFuRFBtLTRyYkZSanNpRWxJSkVSOVRRbTVfT256RmMiLCJraWQiOiJiaWRkaW5nIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIxODY4NDU2MjAxOTczNTgzODcyIiwiYXVkIjoiNWRkZmE2ODJkZWQyZWVjOWI1MGI4OTE5YzhmYTRjNDQiLCJuYmYiOjE3MzY5MjA3NDQsImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzM2OTI3OTQ0LCJpYXQiOjE3MzY5MjA3NDQsImp0aSI6IjY3MGRhNGI2MzhmNzQ1MzA5N2QwNzFlYTRiZGZlMGQxIn0.WtcBESUuk6isQp7Y7Mydpo7rG-mGb6XBT3hTGe-sEJ3Vy158Y0ESQoLMt3uNW4-nM93phsssjjU0WNGs81OOTORlRgUdqKYSFgnvLJrBDD40GapiAabiKNSHGlHU45t-HwM-bMUSx0PDFDNg_upUAnz15l19bF-Q14b3V-WM7FVHKwQWolf0qr0CulMs1lIhgtqadj316j-5jx2I6SJH8Fvvffek_btUiG6RfrjE_lYdk4XjwwKydlMzL8-9Wx4D51Hz8oNXObqSSOxC_CKRTbzXj1ktTkIs-rDTNW35T_fnfbX9nypvg_vA0njqGPaZuAexiPi1yLAmlLU1eqJ-sg
  tpEvalSectionId: '1855906660619333634'
  tpId: '1879407945586229249'
  uploadcashfileid1: $.data.id
  url: http://trade.jy-test.zszc.jianshicha.cn/etbApi/
  username: 招标人ABC
noticeEndTime: 2024-10-01
purchaseMode: null
purchaseProjectName: 测试接口自动化项目
request_headers: {}
request_parameters: {}
server:
  case_severity:
  - P1
  cor_rel_case_severity:
    P1: blocker
    P2: critical
    P3: normal
    P4: minor
    P5: trivial
  test: http://trade.jy-test.zszc.jianshicha.cn/etbApi/
sheet_name: 1-招标-excle
test_case_type:
  dev:
  - file: xlsx
    order: 1
    read: true
    test_case: ./data/env_dev/case_excle/
  - file: yaml
    order: 0
    read: false
    test_case: ./data/env_dev/case_yaml/
  prod:
  - file: xlsx
    order: 1
    read: false
    test_case: ./data/env_prod/case_excle/
  - file: yaml
    order: 0
    read: true
    test_case: ./data/env_prod/case_yaml/
  test:
  - file: xlsx
    order: 1
    read: true
    test_case: ./data/env_test/case_excle/zz
  - file: yaml
    order: 0
    read: false
    test_case: ''
