Operations_db:
  assert_db: true
  backup: false
  recovery: false
bidDocReferEndTime: 2024-10-01
bidDocReferEndTimeCus: 2024-10-01
bidOpenTime: '2024-10-29 15:20:59'
bidSectionName: 测试接口自动化项目标段
case_ids:
  case_id: b30
database:
  dev:
    data:
      database: mydb
      host: 192.168.4.82
      password: zszc
      port: 5432
      user: root
    db_type: postgresql
  prod:
    data:
      database: ry-vue
      host: 192.168.1.234
      password: '123456'
      port: 3306
      user: root
    db_type: mysql
  test:
    data:
      database: qy_biz_open_eval
      host: 192.168.4.82
      password: zszc
      port: 3306
      user: root
    db_type: mysql
docGetEndTime: 2024-10-01
docGetEndTimeCus: 2024-10-01
email:
  addressees:
  - 397135766@qq.com
  - huangpeng245@163.com
  contents: 解压allure-report.zip(接口测试报告)后，进入解压目录，运行Start_server.bat（需要有python环境），在浏览器输入http://127.0.0.1:5188/allure-report
    即可查看测试报告。出现“Serving HTTP on 0.0.0.0 port 5188 (http://0.0.0.0:5188/) ...”表示服务启动完成，可以输入
    http://127.0.0.1:5188/allure-report 地址查看报告
  enclosures: ./report_zip/allure-report.zip
  host: smtp.163.com
  password: DYTKTEPXOZXXZMHK
  title: 接口自动化测试报告(见附件)
  user: huoyan_hyh@163.com
extra_pool:
  Aprtoken: $.data.access_token
  OpenTime: '2024-10-29 15:10:57'
  PROJECT_NAME: $.project_name
  _ERROR: ' 0'
  _FAILED: ' 23'
  _PASSED: '0'
  _SKIPPED: ' 0'
  _SUCCESS_RATE: '0.0'
  _TIMES: 42.43 s
  _TOTAL: '23'
  audittoken: $.data.access_token
  audittoken1: eyJ4NXQjUzI1NiI6Im02OXFnMnMxeE1NQkFuRFBtLTRyYkZSanNpRWxJSkVSOVRRbTVfT256RmMiLCJraWQiOiJiaWRkaW5nIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIxODUzMjUxMDQ5MzU2NDQ3NzQ0IiwiYXVkIjoiNWRkZmE2ODJkZWQyZWVjOWI1MGI4OTE5YzhmYTRjNDQiLCJuYmYiOjE3MzMxMjc0NTksImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMzMTM0NjU5LCJpYXQiOjE3MzMxMjc0NTksImp0aSI6IjA0NzQwNDYwNDE3MjRjM2JiZWExZWM4MmZhZDczNjJjIn0.YPkLfZiCRt4DTLsfh3zg1iKtWvrGB4c5kbnJrwK9a-3ivjVhoaLin9sTrBG3R36pTS58my4NAIe8zDuQUV3-UO8vsKVNxcsK90721RuDBNas2sNhDK5Nb0zvqB2HX-epFN-6EFJLJlXfwsu8Yh8QPG55hMZnzH_5LJ3anPypYdgqMfNIkB45e4XTD4b1M7oxVYkVlBLy1h4hYD6U-4pmCrQ3LUVx6_FgeojZH5Wn6Rtno8yVJnE2ZGj9QVlRT63IOJApICDXXn-Or2TfMBibROrli454hKp9kfmoYPqbgeMSh5TjoXdq2ShBYZb-D4kKtGatH6ZgNQ37dRlkGx8t2w
  bidDocReferEndTime: '2025-02-13 09:53:36'
  bidDocReferEndTimeCus: '2025-02-13 09:53:36'
  bidOpenTime: '2025-02-13 09:53:36'
  bidSectionCode: $.data.list[0].bidSectionCode
  bidSectionId: $.data.list[0].id
  bidSectionName: $.data.list[0].bidSectionName
  bidSectionName1: 测试接口自动化项目2025-01-21 16:31:29-标段01
  bidSectionName2: 测试接口自动化项目2025-01-21 16:31:29-标段02
  bulletinId: $.data.[0].bulletinId
  catalogId: $.data.[0].id
  docGetEndTime: '2025-02-13 09:53:36'
  docGetEndTimeCus: '2025-02-13 09:53:36'
  env: test
  evaluation_method: '1'
  feeCash: ''
  feeCommitment: ''
  feeGuarantee: ''
  fileId: $.data.id
  fileNum: 0
  firstAprPsw: AzCVpjpvyq0KfgdcSO1QfFU9KLEZDCDwa3G3mjlAf4TqT7vdBbtC7XwRW1wt32trPNDC/6rLpXJOmRtalZ5XVJdrgjzahu7X46BSkdgIbsQ7COuwuGe0HAfL_Y3yPjkDfwtLueFSDwAHQjs8tOJmwvFBzpa8DneHOTCUxY/kcwE=
  firstAprUser: trade-audit
  guaranteeType: ''
  ifFee: ''
  ifJudgesConfirmWinBidder: 'false'
  ifSupportBlindBid: 'false'
  ifSupportSmallMicro: 'false'
  ifSyndicatedFlag: 'false'
  ifUseCa: 'false'
  inviteLetter: $.data.[0].id
  inviteType: '2'
  itemid: '1855903699903414273'
  marginPrice: '0'
  marginUnit: '0'
  noticeContentId: $.data[0].tempFileId
  noticeEndTime: '2025-02-13 09:53:36'
  noticeSendTime: '2025-01-24 09:58:36'
  password: Hsad9dPfr0ZfwVGp3Y6nmLaR9d/Ns_KpZ6arW9x8GI1cjx02U25Y8_3H7Zs6BGivBFQkmocPmEet49IXiN1/QY7gvoe8iN3B_87fO0Er5tl/ekyMJe5H3KCtw/MJ2_dr2viRrWAHcViz_AmteXPPls5bVRzdp9nftEv9MlmZbIs=
  pqrMode: '2'
  purchaseMode: '2'
  purchaseProjectCode: $.data.list[0].purchaseProjectCode
  purchaseProjectName: 测试接口自动化项目2025-01-24 09:53:36
  purchaseProjectNameDecode: '%E6%B5%8B%E8%AF%95%E6%8E%A5%E5%8F%A3%E8%87%AA%E5%8A%A8%E5%8C%96%E9%A1%B9%E7%9B%AE2025-01-24%2009%3A53%3A36'
  purchaseProjectType: D01
  purchase_project_code: E1306005456000071001
  tenderOrganizeForm: '1'
  tfId: $.data
  tfPrice: '0'
  tfid: $.data
  token: $.data.access_token
  tpEvalSectionId: '1855906660619333634'
  tpId: $.data.list[0].id
  uploadcashfileid1: $.data.id
  url: http://trade.jy-test.zszc.jianshicha.cn/etbApi/
  username: 招标人AAA
noticeEndTime: 2024-10-01
noticeSendTime: 2024-10-01
purchaseMode: null
purchaseProjectName: 测试接口自动化项目
request_headers: {}
request_parameters: {}
server:
  case_severity:
  - P1
  cor_rel_case_severity:
    P1: blocker
  test: http://trade.jy-test.zszc.jianshicha.cn/etbApi/
sheet_name: 1-招标-excle
test_case_type:
  dev:
  - file: xlsx
    order: 1
    read: true
    test_case: ./data/env_dev/case_excle/
  - file: yaml
    order: 0
    read: false
    test_case: ./data/env_dev/case_yaml/
  prod:
  - file: xlsx
    order: 1
    read: false
    test_case: ./data/env_prod/case_excle/
  - file: yaml
    order: 0
    read: true
    test_case: ./data/env_prod/case_yaml/
  test:
  - file: xlsx
    order: 1
    read: true
    test_case: ./data/env_test/case_excle/zz
  - file: yaml
    order: 0
    read: false
    test_case: ''
